<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>3.3.2.6</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>ADITUS.dotnet-passbook</PackageId>
    <Company>ADITUS</Company>
    <Product>ADITUS.dotnet-passbook</Product>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <Description>Generate pass files for Apple Wallet. This library allows you to build and sign a pkpass file.</Description>
    <PackageReleaseNotes>Fork dotnet-passbook which implement Apple Wallet New Event Ticket</PackageReleaseNotes>
    <PackageTags>PassBook Wallet Apple Passkit</PackageTags>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression></PackageLicenseExpression>
    <RepositoryUrl>https://github.com/vogelsangaditus/dotnet-passbook</RepositoryUrl>
    <Copyright>2025 ADITUS</Copyright>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <AssemblyVersion>3.0.1</AssemblyVersion>
    <FileVersion>3.0.1</FileVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Authors>Tomas McGuinness, Daniel Vogelsang</Authors>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\license.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="5.0.1" />
    <PackageReference Include="System.Text.Json" Version="7.0.0" />
  </ItemGroup>

</Project>
